favicon: null
name: testsite2016
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.2734926098491997
  brandStrength: 0.3991967770271003
  rhythmicContrast: 0.02614823891781271
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  lightness: 0.4458902534097433
typography_spectrum: 0.03829787
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.80303
analytics:
  twitter: null
  google: null
  facebook: null
